# Site wide configuration

title: ENEE244
sub-title: Digital Logic Design
semester: Spring 2015
description:
locale:
url: //enee244.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
gems:
  - jekyll-sitemap

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
